name: TAB-Additions
version: 1.5.14
main: io.github.tanguygab.tabadditions.spigot.TABAdditionsSpigot
api-version: 1.13
depend: [TAB]
softdepend: [PlaceholderAPI,floodgate-bukkit,DiscordSRV,AdvancedBan]
author: Tanguygab
description: More features for the plugin TAB !
commands:
  tabadditions:
    usage: /command
    permission: tabadditions.admin
    aliases: [taba,tabaddon,tab+,tabaddition]
  msg:
    aliases: [m,w,whisper,tell]
  reply:
    aliases: [r]
  togglemsg:
  ignore:
  emojis:
  clearchat:
  socialspy:
  togglemention: