name: TAB-Additions
version: 1.6.1
main: io.github.tanguygab.tabadditions.spigot.TABAdditionsSpigot
api-version: 1.13
depend: [TAB]
softdepend: [PlaceholderAPI,floodgate-bukkit,DiscordSRV,AdvancedBan]
author: Tanguygab
description: More features for the plugin TAB !
commands:
  tabadditions:
    usage: /command
    permission: tabadditions.admin
    aliases: [taba,tabaddon,tab+,tabaddition]
  tab+cmds:
    aliases: [msg,r,reply,togglemsg,ignore,emojis,clearchat]